// <auto-generated />
using System;
using Desafio.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Desafio.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230714133548_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Desafio.Domain.Entities.ImportacaoCNAB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cartao")
                        .IsRequired()
                        .HasColumnName("cartao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnName("cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data")
                        .HasColumnName("data")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataImportacao")
                        .HasColumnName("data_importacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Hora")
                        .HasColumnName("hora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Loja")
                        .IsRequired()
                        .HasColumnName("loja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RepresentanteLoja")
                        .IsRequired()
                        .HasColumnName("representante_loja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnName("tipo")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnName("valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id")
                        .HasName("id");

                    b.ToTable("Importacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
